#*-------------------------------------------------------------------
# This script creates a docker container and initalizes the
# arbitrage-bot so that it can be run in a containerd space.
#
# The docker image builds on the python:<version>-slim image and
# installs Node.js and the git repo for the bot project.
#*-------------------------------------------------------------------


#*-------------------------------------------------------------------
# Stage 0: setup variables for this project

# Construct variables based on ARGs defined above
ARG base_image=ubuntu \
    base_version=latest


#*-------------------------------------------------------------------
# Stage 1: Final image
# keep as flat as possible to limit layers
FROM ${base_image}:${base_version}

# Set the default command to execute
# when creating a new container
CMD ["bash"]

#*-------------------------------------------------------------------
# End Stage(s)
