#*-------------------------------------------------------------------
# This script creates a basic test docker image.
# The docker image builds on the ubuntu:latest image.
#*-------------------------------------------------------------------

#*-------------------------------------------------------------------
# Stage 0: Define ARGs outside of a build stage to parameterize the base image
ARG base_image=ubuntu
ARG base_version=latest

#*-------------------------------------------------------------------
# Stage 1: Final image
# keep as flat as possible to limit layers
FROM ${base_image}:${base_version}

# Set the default command to execute
# when creating a new container
CMD ["bash"]
#*-------------------------------------------------------------------
# End Stage(s)
